name: Budowanie i publikacji

on:
  push:
    branches:
      - main

env:
  PACKAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzenie repozytorium
        uses: actions/checkout@v2

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalacja zależności
        run: npm install

      - name: Budowanie i tagowanie obrazu Docker
        run: |
          docker build -t ghcr.io/wfgen/zadanie2docker:${{ env.PACKAGE_TAG }} -t ghcr.io/wfgen/zadanie2docker:latest .
          docker tag ghcr.io/wfgen/zadanie2docker:${{ env.PACKAGE_TAG }} ghcr.io/wfgen/zadanie2docker:latest

      - name: Wysyłanie obrazu Docker
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/wfgen/zadanie2docker:${{ env.PACKAGE_TAG }}
          docker push ghcr.io/wfgen/zadanie2docker:latest

      - name: Ustawianie metadanych obrazu
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/wfgen/zadanie2docker

      - name: Odczyt wersji obrazu
        uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/wfgen/zadanie2docker

      - name: Wyświetlanie wersji obrazu
        run: echo "IMAGE_VERSION=${{ steps.metadata.outputs.tags }}" >> $GITHUB_ENV

